### Razor Kenway SL Android (Sri Lanka 🇱🇰 )👋

<!--
**RazorKenway/RazorKenway** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->

eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('<0 1="2"><3 4="5://6-7-8.9.a/b?c=d&&e=f&g=h&i=j&k=l&m=n">',24,24,'p|align|center|img|src|https|github|readme|stats|vercel|app|api|username|RazorKenway|show_icons|true|title_color|ffffff|icon_color|bb2acf|text_color|daf7dc|bg_color|151515'.split('|'),0,{}))
